version: '3'
services:
  DO:
    restart: always
    environment:
     - DOPASS=
     - Donate_portion_of_staking=0.1
    volumes:
     - ./DeepOnionConf:/root/.DeepOnion
    image: morecoin/deeponion
